apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namePrefix: dev-
resources:
  - ../../nginx-app
patchesStrategicMerge:
  - replica_count.yaml
  - resource_limits.yaml
  - env.yaml
configMapGenerator:
  - name: nginx-config
    files:
      - configs/index.html
images:
  - name: nginx
    newTag: 1.21.1
#namespace: dev