apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment
spec:
  template:
    spec:
      containers:
      - name: nginx
        resources:
          requests:
            memory: "800Mi"
            cpu: "250m"
          limits:
            memory: "800Mi"
            cpu: "250m"